const keyboardObject = [
  { // первый ряд
    Backquote: {
      en_lower: '`',
      en_upper: '~',
      ru_lower: 'ё',
      ru_upper: 'Ё',
    },
    Digit1: {
      en_lower: '1',
      en_upper: '!',
      ru_lower: '1',
      ru_upper: '!',
    },
    Digit2: {
      en_lower: '2',
      en_upper: '@',
      ru_lower: '2',
      ru_upper: '"',
    },
    Digit3: {
      en_lower: '3',
      en_upper: '#',
      ru_lower: '3',
      ru_upper: '№',
    },
    Digit4: {
      en_lower: '4',
      en_upper: '$',
      ru_lower: '4',
      ru_upper: ';',
    },
    Digit5: {
      en_lower: '5',
      en_upper: '%',
      ru_lower: '5',
      ru_upper: '%',
    },
    Digit6: {
      en_lower: '6',
      en_upper: '^',
      ru_lower: '6',
      ru_upper: ':',
    },
    Digit7: {
      en_lower: '7',
      en_upper: '&',
      ru_lower: '7',
      ru_upper: '?',
    },
    Digit8: {
      en_lower: '8',
      en_upper: '*',
      ru_lower: '8',
      ru_upper: '*',
    },
    Digit9: {
      en_lower: '9',
      en_upper: '(',
      ru_lower: '9',
      ru_upper: '(',
    },
    Digit0: {
      en_lower: '0',
      en_upper: ')',
      ru_lower: '0',
      ru_upper: ')',
    },
    Minus: {
      en_lower: '-',
      en_upper: '_',
      ru_lower: '-',
      ru_upper: '_',
    },
    Equal: {
      en_lower: '=',
      en_upper: '+',
      ru_lower: '=',
      ru_upper: '+',
    },
    Backspace: {
      en_lower: 'Backspace',
      en_upper: 'Backspace',
      ru_lower: 'Backspace',
      ru_upper: 'Backspace',
      width: '100px',
    },
  },
  { // второй ряд
    Tab: {
      en_lower: 'Tab',
      en_upper: 'Tab',
      ru_lower: 'Tab',
      ru_upper: 'Tab',
      width: '50px',
    },
    KeyQ: {
      en_lower: 'q',
      en_upper: 'Q',
      ru_lower: 'й',
      ru_upper: 'Й',
    },
    KeyW: {
      en_lower: 'w',
      en_upper: 'W',
      ru_lower: 'ц',
      ru_upper: 'Ц',
    },
    KeyE: {
      en_lower: 'e',
      en_upper: 'E',
      ru_lower: 'у',
      ru_upper: 'У',
    },
    KeyR: {
      en_lower: 'r',
      en_upper: 'R',
      ru_lower: 'к',
      ru_upper: 'К',
    },
    KeyT: {
      en_lower: 't',
      en_upper: 'T',
      ru_lower: 'е',
      ru_upper: 'Е',
    },
    KeyY: {
      en_lower: 'y',
      en_upper: 'Y',
      ru_lower: 'н',
      ru_upper: 'Н',
    },
    KeyU: {
      en_lower: 'u',
      en_upper: 'U',
      ru_lower: 'г',
      ru_upper: 'Г',
    },
    KeyI: {
      en_lower: 'i',
      en_upper: 'I',
      ru_lower: 'ш',
      ru_upper: 'Ш',
    },
    KeyO: {
      en_lower: 'o',
      en_upper: 'O',
      ru_lower: 'щ',
      ru_upper: 'Щ',
    },
    KeyP: {
      en_lower: 'p',
      en_upper: 'P',
      ru_lower: 'з',
      ru_upper: 'З',
    },
    BracketLeft: {
      en_lower: '[',
      en_upper: '{',
      ru_lower: 'х',
      ru_upper: 'Х',
    },
    BracketRight: {
      en_lower: ']',
      en_upper: '}',
      ru_lower: 'ъ',
      ru_upper: 'Ъ',
    },
    Backslash: {
      en_lower: '\\',
      en_upper: '|',
      ru_lower: '\\',
      ru_upper: '/',
    },
    Delete: {
      en_lower: 'Del',
      en_upper: 'Del',
      ru_lower: 'Del',
      ru_upper: 'Del',
    },
  },
  { // третий ряд
    CapsLock: {
      en_lower: 'CapsLock',
      en_upper: 'CapsLock',
      ru_lower: 'CapsLock',
      ru_upper: 'CapsLock',
      width: '100px',
    },
    KeyA: {
      en_lower: 'a',
      en_upper: 'A',
      ru_lower: 'ф',
      ru_upper: 'Ф',
    },
    KeyS: {
      en_lower: 's',
      en_upper: 'S',
      ru_lower: 'ы',
      ru_upper: 'Ы',
    },
    KeyD: {
      en_lower: 'd',
      en_upper: 'D',
      ru_lower: 'в',
      ru_upper: 'В',
    },
    KeyF: {
      en_lower: 'f',
      en_upper: 'F',
      ru_lower: 'а',
      ru_upper: 'А',
    },
    KeyG: {
      en_lower: 'g',
      en_upper: 'G',
      ru_lower: 'п',
      ru_upper: 'П',
    },
    KeyH: {
      en_lower: 'h',
      en_upper: 'H',
      ru_lower: 'р',
      ru_upper: 'Р',
    },
    KeyJ: {
      en_lower: 'j',
      en_upper: 'J',
      ru_lower: 'о',
      ru_upper: 'О',
    },
    KeyK: {
      en_lower: 'k',
      en_upper: 'K',
      ru_lower: 'л',
      ru_upper: 'Л',
    },
    KeyL: {
      en_lower: 'l',
      en_upper: 'L',
      ru_lower: 'д',
      ru_upper: 'Д',
    },
    Semicolon: {
      en_lower: ';',
      en_upper: ':',
      ru_lower: 'ж',
      ru_upper: 'Ж',
    },
    Quote: {
      en_lower: '\'',
      en_upper: '"',
      ru_lower: 'э',
      ru_upper: 'Э',
    },
    Enter: {
      en_lower: 'Enter',
      en_upper: 'Enter',
      ru_lower: 'Enter',
      ru_upper: 'Enter',
      width: '90px',
    },
  },
  { // четвертый ряд
    ShiftLeft: {
      en_lower: 'Shift',
      en_upper: 'Shift',
      ru_lower: 'Shift',
      ru_upper: 'Shift',
      width: '100px',
    },
    KeyZ: {
      en_lower: 'z',
      en_upper: 'Z',
      ru_lower: 'я',
      ru_upper: 'Я',
    },
    KeyX: {
      en_lower: 'x',
      en_upper: 'X',
      ru_lower: 'ч',
      ru_upper: 'Ч',
    },
    KeyC: {
      en_lower: 'c',
      en_upper: 'C',
      ru_lower: 'с',
      ru_upper: 'С',
    },
    KeyV: {
      en_lower: 'v',
      en_upper: 'V',
      ru_lower: 'м',
      ru_upper: 'М',
    },
    KeyB: {
      en_lower: 'b',
      en_upper: 'B',
      ru_lower: 'и',
      ru_upper: 'И',
    },
    KeyN: {
      en_lower: 'n',
      en_upper: 'N',
      ru_lower: 'т',
      ru_upper: 'Т',
    },
    KeyM: {
      en_lower: 'm',
      en_upper: 'M',
      ru_lower: 'ь',
      ru_upper: 'Ь',
    },
    Comma: {
      en_lower: ',',
      en_upper: '<',
      ru_lower: 'б',
      ru_upper: 'Б',
    },
    Period: {
      en_lower: '.',
      en_upper: '>',
      ru_lower: 'ю',
      ru_upper: 'Ю',
    },
    Slash: {
      en_lower: '/',
      en_upper: '?',
      ru_lower: '.',
      ru_upper: ',',
    },
    ArrowUp: {
      en_lower: '▲',
      en_upper: '▲',
      ru_lower: '▲',
      ru_upper: '▲',
    },
    ShiftRight: {
      en_lower: 'Shift',
      en_upper: 'Shift',
      ru_lower: 'Shift',
      ru_upper: 'Shift',
      width: '90px',
    },
  },
  { // пятый ряд
    ControlLeft: {
      en_lower: 'Ctrl',
      en_upper: 'Ctrl',
      ru_lower: 'Ctrl',
      ru_upper: 'Ctrl',
    },
    MetaLeft: {
      en_lower: 'Win',
      en_upper: 'Win',
      ru_lower: 'Win',
      ru_upper: 'Win',
    },
    AltLeft: {
      en_lower: 'Alt',
      en_upper: 'Alt',
      ru_lower: 'Alt',
      ru_upper: 'Alt',
    },
    Space: {
      en_lower: ' ',
      en_upper: ' ',
      ru_lower: ' ',
      ru_upper: ' ',
      width: '372px',
    },
    AltRight: {
      en_lower: 'Alt',
      en_upper: 'Alt',
      ru_lower: 'Alt',
      ru_upper: 'Alt',
    },
    ArrowLeft: {
      en_lower: '◄',
      en_upper: '◄',
      ru_lower: '◄',
      ru_upper: '◄',
    },
    ArrowDown: {
      en_lower: '▼',
      en_upper: '▼',
      ru_lower: '▼',
      ru_upper: '▼',
    },
    ArrowRight: {
      en_lower: '►',
      en_upper: '►',
      ru_lower: '►',
      ru_upper: '►',
    },
    ControlRight: {
      en_lower: 'Ctrl',
      en_upper: 'Ctrl',
      ru_lower: 'Ctrl',
      ru_upper: 'Ctrl',
    },
  },
];

export default keyboardObject;
